local passType = {
	Gamepass = 1,
	Shirt = 2
}

return {
	{
		Name = "Volvo B8L (Wright Gemini 3)",
		ModelName = "MEX Volvo B8L 11.3m (5410-5424)",
		AssetId = 95863253707197, -- REPLACE 0 WITH THE MODEL ID FROM ROBLOX
		Image = "rbxassetid://82952276526772",
		SpawnBayName = "AlyslynNorth",
		IsGamepass = false,
		GamepassId = 0,
		GamepassType = passType.Gamepass
	},
	{
		Name = "ADL Enviro 200 Dart 10.2m",
		ModelName = "MEX E200 (Borrow)",
		AssetId = 90922073105241, -- REPLACE 0 WITH THE MODEL ID FROM ROBLOX
		Image = "rbxassetid://82952276526772",
		SpawnBayName = "AlyslynNorth",
		IsGamepass = false,
		GamepassId = 0,
		GamepassType = passType.Gamepass
	}
}
