local passType = {
	Gamepass = 1,
	Shirt = 2
}

return {
	{
		Name = "Man 14.220 Euro 3",
		ModelName = "Man 14.220 Euro 3",
		AssetId = 119186868936720, -- REPLACE 0 WITH THE MODEL ID FROM ROBLOX
		Image = "rbxassetid://7495521129",
		SpawnBayName = "Sainsley",
		IsGamepass = false,
		GamepassId = 0,
		GamepassType = passType.Gamepass
	},
	{
		Name = "Volvo B8RLE",
		ModelName = "Volvo B8RLE",
		AssetId = 91981893673476, -- REPLACE 0 WITH THE MODEL ID FROM ROBLOX
		Image = "rbxassetid://7495521129",
		SpawnBayName = "Sainsley",
		IsGamepass = false,
		GamepassId = 0,
		GamepassType = passType.Gamepass
	},
	{
		Name = "Wright Streetdeck",
		ModelName = "MTB Streetdeck",
		AssetId = 89752845058181, -- REPLACE 0 WITH THE MODEL ID FROM ROBLOX
		Image = "rbxassetid://7495521129",
		SpawnBayName = "Sainsley",
		IsGamepass = false,
		GamepassId = 0,
		GamepassType = passType.Gamepass
	},
	{
		Name = "Enviro 200 9.7m (Facelift)",
		ModelName = "ML_E200_DEM",
		AssetId = 91107191858790, -- REPLACE 0 WITH THE MODEL ID FROM ROBLOX
		Image = "rbxassetid://7495521129",
		SpawnBayName = "Sainsley",
		IsGamepass = false,
		GamepassId = 0,
		GamepassType = passType.Gamepass
	},
	{
		Name = "Dennis Trident 10.6m (TAL1-25)",
		ModelName = "ALX400_LH_TAL1-25",
		AssetId = 130737206842771, -- REPLACE 0 WITH THE MODEL ID FROM ROBLOX
		Image = "rbxassetid://7495521129",
		SpawnBayName = "Sainsley",
		IsGamepass = false,
		GamepassId = 0,
		GamepassType = passType.Gamepass
	},
	{
		Name = "[Metrobus VIP] Enviro 400 (TE1, Sainsley Ambassador Livery)",
		ModelName = "Enviro400_TE1",
		AssetId = 131923927012285, -- REPLACE 0 WITH THE MODEL ID FROM ROBLOX
		Image = "rbxassetid://7495521129",
		SpawnBayName = "Sainsley",
		IsGamepass = false,
		GamepassId = 0,
		GamepassType = passType.Gamepass
	},
	{
		Name = "Enviro 400 (TE2-20)",
		ModelName = "Enviro400_ExMTL_TE2-20",
		AssetId = 101713290099208, -- REPLACE 0 WITH THE MODEL ID FROM ROBLOX
		Image = "rbxassetid://7495521129",
		SpawnBayName = "Sainsley",
		IsGamepass = false,
		GamepassId = 0,
		GamepassType = passType.Gamepass
	},
}



