local passType = {
	Gamepass = 1,
	Shirt = 2
}

return {
	{
		Name = "Volvo BZL SD 10.35m",
		ModelName = "BZL_10.3m_MB_14xx",
		AssetId = 127507537564207, -- REPLACE 0 WITH THE MODEL ID FROM ROBLOX
		Image = "rbxassetid://12555633409",
		SpawnBayName = "Snerdan",
		IsGamepass = false,
		GamepassId = 0,
		GamepassType = passType.Gamepass
	},
	{
		Name = "ADL Enviro 200 MMC 10.8m",
		ModelName = "E200MMC_MB_10800_COD",
		AssetId = 138148758057270, -- REPLACE 0 WITH THE MODEL ID FROM ROBLOX
		Image = "rbxassetid://12555633409",
		SpawnBayName = "Snerdan",
		IsGamepass = false,
		GamepassId = 0,
		GamepassType = passType.Gamepass
	},	
	{
		Name = "ADL Enviro 200 MMC 9.75m",
		ModelName = "E200MMC_MB_9750_COD",
		AssetId = 70761887924353, -- REPLACE 0 WITH THE MODEL ID FROM ROBLOX
		Image = "rbxassetid://12555633409",
		SpawnBayName = "Snerdan",
		IsGamepass = false,
		GamepassId = 0,
		GamepassType = passType.Gamepass
	}
}
