local passType = {
	Gamepass = 1,
	Shirt = 2
}

return {
	{
		Name = "GGB Volvo B8RLE",
		ModelName = "GGB Volvo B8RLE YN Normal",
		AssetId = 138087466808086, -- REPLACE 0 WITH THE MODEL ID FROM ROBLOX
		Image = "rbxassetid://14803703648",
		SpawnBayName = "TerranGreen",
		IsGamepass = false,
		GamepassId = 0,
		GamepassType = passType.Gamepass
	},	
	{
		Name = "Dennis Dart (Single Door)",
		ModelName = "MTB_DL",
		AssetId = 132588739472803, -- REPLACE 0 WITH THE MODEL ID FROM ROBLOX
		Image = "rbxassetid://7495521129",
		SpawnBayName = "TerranGreen",
		IsGamepass = false,
		GamepassId = 0,
		GamepassType = passType.Gamepass
	},
	{
		Name = "Man 14.220 Euro 4",
		ModelName = "Man 14.220 Euro 4",
		AssetId = 114783648754046, -- REPLACE 0 WITH THE MODEL ID FROM ROBLOX
		Image = "rbxassetid://7495521129",
		SpawnBayName = "TerranGreen",
		IsGamepass = false,
		GamepassId = 0,
		GamepassType = passType.Gamepass
	}
}



